---

version: '3'

services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    # ACHTUNG! JEDES DOLLAR-ZEICHEN "$" muss verdoppelt werden: "$" --> "$$"
    # Default Hash: $$2y$$05$$mCLVgk.bwtDsBMkF66lyJOPh.xDEPrVSXpvoLopizy2FhFMGj5Juy
    # Clear Text: Passw0rd!
    command: --admin-password "$$2y$$05$$mCLVgk.bwtDsBMkF66lyJOPh.xDEPrVSXpvoLopizy2FhFMGj5Juy"
volumes:
  portainer_data: