---
- name: Kubernetes cluster initialisation
  remote_user: opsroot
  become: true
  become_user: root
  include_vars: 
    file: "../../vars/cluster_vars.yml"
    name: cluster_vars

  tasks:
    - name: Install Bash auto-completion
      hosts: master_nodes
      yum:
        name: bash-completion
        state: present

    - name: activate tab-completion for kubectl
      hosts: master_nodes
      lineinfile:
        path: /root/.bashrc
        line: 'source <(kubectl completion bash)'

    - name: set aliases for kubectl
      hosts: master_nodes
      lineinfile:
        path: /root/.bashrc
        line: '{{ item }}'
      with_items:
        - '# Alias for kubectl'
        - 'alias kc="kubectl create --validate -f"'
        - 'alias kg="kubectl get"'
        - 'alias kgs="kubectl get -n=kube-system"'
        - 'alias kga="kubectl get --all-namespaces"'
        - 'alias kgall="kubectl get all --all-namespaces"'
        - 'alias ks="kubectl -n kube-system"'

    - name: source bashrc for aliases
      hosts: master_nodes
      shell: |
        source /root/.bashrc

    - name: Cluster initialisation
      hosts: "{{ cluster_vars.master_node_addr }}"
      shell: |
        kubeadm init --apiserver-advertise-address={{ cluster_vars.master_node_addr }} --pod-network-cidr={{ cluster_vars.pod_network_cidr }}
      register: kubeadm_init
      vars:
        join_cmd: "{{ kubeadm_init.stdout_lines[-1] }}"

    - name: Save join_cmd
      hosts: "{{ cluster_vars.master_node_addr }}"
      copy:
        dest: "/root/join_cmd.txt"
        content: |
          {{ join_cmd }}

    - name: copy Kubernetes config to home
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config

    - name: install flannel
      hosts: master_nodes
      shell: |
        mkdir ~/flannel
        cd ~/flannel
        wget https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml -O ~/flannel/kube-flannel.yml

    - name: add enp0s8 interface to flannel
      hosts: master_nodes
      lineinfile:
        path: ~/flannel/kube-flannel.yml
        line: '        - --iface=enp0s8'
        insertafter: '.*\- \-\-kube-subnet-mgr'
    
    - name: deploy flannel
      hosts: master_nodes
      shell: |
        kubectl apply -f ~/flannel/kube-flannel.yml

    - name: join worker-nodes
      hosts: worker_nodes
      shell: |
        {{ join_cmd }}

