---
# Hosts-datei anpassen: https://www.middlewareinventory.com/blog/ansible-update-etc-hosts-file-across-all-hosts/
# SSH-Key generieren und verteilen: https://www.middlewareinventory.com/blog/ansible-ssh-key-exchange/
- name: "Prepare/configure CentOs for Kubernetes"
  hosts: all
  remote_user: opsroot
  gather_facts: true

  tasks:
  - name: SSH KeyGen command
    shell: > 
      ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
      creates="~/.ssh/id_rsa"

  - name: Fetch the keyfile from the node to master
    fetch: 
      src: "~/.ssh/id_rsa.pub"
      dest: "buffer/{{ansible_hostname}}-id_rsa.pub"
      flat: yes

  - name: Copy the key add to authorized_keys using Ansible module
    authorized_key:
      user: opsroot
      state: present
      key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}"
    when: "{{ item != ansible_hostname }}"
    with_items: 
      - "{{ groups['all'] }}"   

  - name: Update the /etc/hosts file with node name
    tags: etchostsupdate
    become: true
    become_user: root
    lineinfile:
      path: "/etc/hosts"
      regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
      line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
      state: present
      backup: true
    register: etchostsupdate
    when: ansible_hostname != "{{ item }}" or ansible_hostname == "{{ item }}"
    with_items: "{{groups['all']}}"

